# Generated by Django 3.2.4 on 2021-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('year_of_graduation', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('certificate_type', models.CharField(max_length=100)),
            ],
        ),
    ]
