# Generated by Django 3.2.4 on 2021-06-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='default_school_name', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='student',
            field=models.ForeignKey(default='default_student_name', on_delete=django.db.models.deletion.PROTECT, to='SchoolProject.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SchoolProject.student')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SchoolProject.student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SchoolProject.student')),
            ],
        ),
    ]
