# Generated by Django 3.2.4 on 2021-06-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProject', '0002_auto_20210611_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SchoolProject.student'),
        ),
    ]
