# Generated by Django 3.2.4 on 2021-06-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProject', '0003_alter_school_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate_type',
            old_name='certificate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
    ]
